#!/usr/bin/python3

import sys
import json

def help_message():
    print('Wrong option')
    print('Usage:./cmd_man -[als] argument')
    print('Examples:')
    print('./cmd_man -a "command:description"')
    print('./cmd_man -l')
    print('./cmd_man -s "ip"')

try:
    if sys.argv[1] == "-a":
        lst=sys.argv[2].split(":")
        with open("commands.json","r") as fd:
            data = fd.read()
            if data and data is not None:
                data = json.loads(data)
            else:
                data = []
            with open("commands.json","w") as fdw:
                    data.append(lst)
                    fdw.write(json.dumps(data))
    elif sys.argv[1] == "-l":
        with open("commands.json","r") as fd:
            data = fd.read()
            if data:
                for i in json.loads(data):
                    print(f"{i[0]} : {i[1].strip()}")
            else:
                print("No Info")
    elif sys.argv[1] == "-k":
        with open("commands.json","r") as fd:
            data = fd.read()
            if data:
                for i in json.loads(data):
                    temp=list(filter(lambda x: x.lower() in i[1].lower() , sys.argv[2].split(" ")))
                    if temp:
                        print(f"{i[0]} : {i[1]}")
                    else:
                        continue
    else:
        help_message()
except:
    help_message()